using System.Collections.Generic;
using System.Text;
using BreadPack.NativeLua.Generator.Util;

namespace BreadPack.NativeLua.Generator.Module
{
    internal static class ModuleCEmitter
    {
        public static string Emit(ModuleInfo info)
        {
            var sb = new StringBuilder();
            sb.AppendLine("/* <auto-generated/> */");
            sb.AppendLine("#include \"lua.h\"");
            sb.AppendLine("#include \"lauxlib.h\"");
            sb.AppendLine();

            // Extern declaration for function pointer lookup
            sb.AppendLine("extern void* breadlua_get_fn(const char* name);");
            sb.AppendLine();

            // Function pointer typedefs and Lua wrapper functions
            foreach (var m in info.Methods)
            {
                string fnPtrType = "fn_" + info.LuaModuleName + "_" + m.LuaName + "_t";
                string cReturn = TypeMapper.ToCType(m.ReturnType);
                string cParams = BuildCParams(m);

                sb.AppendLine("typedef " + cReturn + " (*" + fnPtrType + ")(" + cParams + ");");
                sb.AppendLine();

                // Lua wrapper function
                sb.AppendLine("static int l_" + info.LuaModuleName + "_" + m.LuaName + "(lua_State* L) {");
                sb.AppendLine("    " + fnPtrType + " fn = (" + fnPtrType + ")breadlua_get_fn(\"" + info.LuaModuleName + "." + m.LuaName + "\");");
                sb.AppendLine("    if (!fn) { return luaL_error(L, \"function not registered: " + info.LuaModuleName + "." + m.LuaName + "\"); }");

                // Extract parameters from Lua stack
                int paramIdx = 1;
                foreach (var p in m.Parameters)
                {
                    string cType = MapParamC(p.CsType);
                    string luaGet = GetLuaParam(p.CsType, paramIdx);
                    sb.AppendLine("    " + cType + " p_" + p.Name + " = " + luaGet + ";");
                    paramIdx++;
                }

                // Call function pointer
                string callArgs = BuildCallArgsC(m);
                if (m.ReturnType == "void")
                {
                    sb.AppendLine("    fn(" + callArgs + ");");
                    sb.AppendLine("    return 0;");
                }
                else
                {
                    sb.AppendLine("    " + TypeMapper.ToCType(m.ReturnType) + " result = fn(" + callArgs + ");");
                    sb.AppendLine("    " + TypeMapper.ToLuaPush(m.ReturnType) + "(L, result);");
                    sb.AppendLine("    return 1;");
                }
                sb.AppendLine("}");
                sb.AppendLine();
            }

            // luaL_Reg table
            sb.AppendLine("static const luaL_Reg " + info.LuaModuleName + "_module_lib[] = {");
            foreach (var m in info.Methods)
            {
                sb.AppendLine("    {\"" + m.LuaName + "\", l_" + info.LuaModuleName + "_" + m.LuaName + "},");
            }
            sb.AppendLine("    {NULL, NULL}");
            sb.AppendLine("};");
            sb.AppendLine();

            sb.AppendLine("int luaopen_" + info.LuaModuleName + "(lua_State* L) {");
            sb.AppendLine("    luaL_newlib(L, " + info.LuaModuleName + "_module_lib);");
            sb.AppendLine("    return 1;");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string MapParamC(string csType)
        {
            switch (csType)
            {
                case "string": return "const char*";
                default: return TypeMapper.ToCType(csType);
            }
        }

        private static string BuildCParams(ExportedMethod m)
        {
            if (m.Parameters.Count == 0) return "void";
            var parts = new List<string>();
            foreach (var p in m.Parameters)
            {
                parts.Add(MapParamC(p.CsType) + " " + p.Name);
            }
            return string.Join(", ", parts);
        }

        private static string GetLuaParam(string csType, int idx)
        {
            switch (csType)
            {
                case "string": return "luaL_checkstring(L, " + idx + ")";
                case "bool": return "lua_toboolean(L, " + idx + ")";
                default: return TypeMapper.ToCCast(csType) + TypeMapper.ToLuaCheck(csType) + "(L, " + idx + ")";
            }
        }

        private static string BuildCallArgsC(ExportedMethod m)
        {
            var parts = new List<string>();
            foreach (var p in m.Parameters)
            {
                parts.Add("p_" + p.Name);
            }
            return string.Join(", ", parts);
        }
    }
}
