using System.Collections.Generic;
using System.Text;

namespace BreadPack.NativeLua.Generator.Module
{
    internal static class ModuleCSharpEmitter
    {
        public static string Emit(ModuleInfo info)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Runtime.InteropServices;");
            sb.AppendLine("using BreadPack.NativeLua;");
            sb.AppendLine("using BreadPack.NativeLua.Native;");
            sb.AppendLine();
            sb.AppendLine("namespace " + info.Namespace);
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class " + info.ClassName);
            sb.AppendLine("    {");

            // Generate delegate types and static fields to prevent GC collection
            foreach (var m in info.Methods)
            {
                string delegateType = "BreadDelegate_" + m.CsName;
                string delegateParams = BuildDelegateParams(m);

                sb.AppendLine("        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]");
                sb.AppendLine("        private delegate " + MapReturnTypeForDelegate(m.ReturnType) + " " + delegateType + "(" + delegateParams + ");");
                sb.AppendLine("        private static " + delegateType + " _delegate_" + m.CsName + ";");
                sb.AppendLine();
            }

            // Generate Register method
            sb.AppendLine("        public static void Register()");
            sb.AppendLine("        {");
            foreach (var m in info.Methods)
            {
                string delegateType = "BreadDelegate_" + m.CsName;
                string wrapperName = "Wrapper_" + m.CsName;
                sb.AppendLine("            _delegate_" + m.CsName + " = new " + delegateType + "(" + wrapperName + ");");
                sb.AppendLine("            var ptr_" + m.CsName + " = Marshal.GetFunctionPointerForDelegate(_delegate_" + m.CsName + ");");
                sb.AppendLine("            LuaNative.breadlua_register_fn(\"" + info.LuaModuleName + "." + m.LuaName + "\", ptr_" + m.CsName + ");");
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            // Generate wrapper methods (Cdecl-compatible)
            foreach (var m in info.Methods)
            {
                string wrapperParams = BuildDelegateParams(m);
                string returnType = MapReturnTypeForDelegate(m.ReturnType);
                sb.AppendLine("        private static " + returnType + " Wrapper_" + m.CsName + "(" + wrapperParams + ")");
                sb.AppendLine("        {");

                string callArgs = BuildCallArgs(m);
                if (m.ReturnType == "void")
                {
                    sb.AppendLine("            " + m.CsName + "(" + callArgs + ");");
                }
                else if (m.ReturnType == "bool")
                {
                    sb.AppendLine("            return " + m.CsName + "(" + callArgs + ") ? 1 : 0;");
                }
                else
                {
                    sb.AppendLine("            return " + m.CsName + "(" + callArgs + ");");
                }
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string BuildDelegateParams(ExportedMethod m)
        {
            var parts = new List<string>();
            foreach (var p in m.Parameters)
            {
                parts.Add(MapParamTypeForDelegate(p.CsType) + " " + p.Name);
            }
            return string.Join(", ", parts);
        }

        private static string BuildCallArgs(ExportedMethod m)
        {
            var parts = new List<string>();
            foreach (var p in m.Parameters)
            {
                if (p.CsType == "string")
                {
                    parts.Add("Marshal.PtrToStringAnsi(" + p.Name + ")");
                }
                else if (p.CsType == "bool")
                {
                    parts.Add(p.Name + " != 0");
                }
                else
                {
                    parts.Add(p.Name);
                }
            }
            return string.Join(", ", parts);
        }

        private static string MapParamTypeForDelegate(string csType)
        {
            switch (csType)
            {
                case "string": return "IntPtr";
                case "bool": return "int";
                case "float": return "float";
                case "double": return "double";
                case "int": return "int";
                case "long": return "long";
                default: return csType;
            }
        }

        private static string MapReturnTypeForDelegate(string csType)
        {
            switch (csType)
            {
                case "void": return "void";
                case "bool": return "int";
                case "float": return "float";
                case "double": return "double";
                case "int": return "int";
                case "long": return "long";
                case "string": return "IntPtr";
                default: return csType;
            }
        }
    }
}
