using System.Collections.Generic;
using System.Text;

namespace BreadPack.NativeLua.Generator.Bind
{
    internal static class BindCSharpEmitter
    {
        public static string Emit(BindClassInfo info)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Runtime.InteropServices;");
            sb.AppendLine("using BreadPack.NativeLua;");
            sb.AppendLine("using BreadPack.NativeLua.Native;");
            sb.AppendLine();
            sb.AppendLine("namespace " + info.Namespace);
            sb.AppendLine("{");
            sb.AppendLine("    public partial class " + info.ClassName);
            sb.AppendLine("    {");
            sb.AppendLine("        public const string LuaMetatableName = \"bread_" + info.ClassName + "\";");
            sb.AppendLine();

            // Release delegate (always needed for __gc)
            EmitRelease(sb);

            // Constructor
            if (info.Constructor != null)
            {
                EmitConstructor(sb, info);
            }

            // Property getters
            foreach (var prop in info.Properties)
            {
                if (prop.HasGetter)
                {
                    EmitPropertyGetter(sb, info, prop);
                }
            }

            // Property setters
            foreach (var prop in info.Properties)
            {
                if (prop.HasSetter)
                {
                    EmitPropertySetter(sb, info, prop);
                }
            }

            // Methods
            foreach (var m in info.Methods)
            {
                EmitMethod(sb, info, m);
            }

            // Register method
            EmitRegister(sb, info);

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void EmitRelease(StringBuilder sb)
        {
            sb.AppendLine("        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]");
            sb.AppendLine("        private delegate void ReleaseDelegate(IntPtr handle);");
            sb.AppendLine("        private static ReleaseDelegate _releaseDelegate;");
            sb.AppendLine();
            sb.AppendLine("        private static void NativeRelease(IntPtr handle)");
            sb.AppendLine("        {");
            sb.AppendLine("            ObjectHandle.Free(handle);");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void EmitConstructor(StringBuilder sb, BindClassInfo info)
        {
            string delegateParams = BuildNativeParams(info.Constructor.Parameters);

            sb.AppendLine("        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]");
            sb.AppendLine("        private delegate IntPtr ConstructorDelegate(" + delegateParams + ");");
            sb.AppendLine("        private static ConstructorDelegate _ctorDelegate;");
            sb.AppendLine();
            sb.AppendLine("        private static IntPtr NativeConstructor(" + delegateParams + ")");
            sb.AppendLine("        {");
            string ctorArgs = BuildCallArgs(info.Constructor.Parameters);
            sb.AppendLine("            var obj = new " + info.ClassName + "(" + ctorArgs + ");");
            sb.AppendLine("            return ObjectHandle.Alloc(obj);");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void EmitPropertyGetter(StringBuilder sb, BindClassInfo info, BindPropertyInfo prop)
        {
            string nativeReturn = MapNativeType(prop.CsType);
            string fieldName = "_get_" + prop.CsName;

            sb.AppendLine("        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]");
            sb.AppendLine("        private delegate " + nativeReturn + " Get" + prop.CsName + "Delegate(IntPtr handle);");
            sb.AppendLine("        private static Get" + prop.CsName + "Delegate " + fieldName + ";");
            sb.AppendLine();
            sb.AppendLine("        private static " + nativeReturn + " NativeGet" + prop.CsName + "(IntPtr handle)");
            sb.AppendLine("        {");
            sb.AppendLine("            var obj = ObjectHandle.Get<" + info.ClassName + ">(handle);");
            if (prop.CsType == "string")
            {
                sb.AppendLine("            return obj != null ? Marshal.StringToHGlobalAnsi(obj." + prop.CsName + ") : IntPtr.Zero;");
            }
            else if (prop.CsType == "bool")
            {
                sb.AppendLine("            return obj != null && obj." + prop.CsName + " ? 1 : 0;");
            }
            else
            {
                sb.AppendLine("            return obj != null ? obj." + prop.CsName + " : default;");
            }
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void EmitPropertySetter(StringBuilder sb, BindClassInfo info, BindPropertyInfo prop)
        {
            string nativeParam = MapNativeType(prop.CsType);
            string fieldName = "_set_" + prop.CsName;

            sb.AppendLine("        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]");
            sb.AppendLine("        private delegate void Set" + prop.CsName + "Delegate(IntPtr handle, " + nativeParam + " value);");
            sb.AppendLine("        private static Set" + prop.CsName + "Delegate " + fieldName + ";");
            sb.AppendLine();
            sb.AppendLine("        private static void NativeSet" + prop.CsName + "(IntPtr handle, " + nativeParam + " value)");
            sb.AppendLine("        {");
            sb.AppendLine("            var obj = ObjectHandle.Get<" + info.ClassName + ">(handle);");
            sb.AppendLine("            if (obj == null) return;");
            if (prop.CsType == "string")
            {
                sb.AppendLine("            obj." + prop.CsName + " = Marshal.PtrToStringAnsi(value);");
            }
            else if (prop.CsType == "bool")
            {
                sb.AppendLine("            obj." + prop.CsName + " = value != 0;");
            }
            else
            {
                sb.AppendLine("            obj." + prop.CsName + " = value;");
            }
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void EmitMethod(StringBuilder sb, BindClassInfo info, BindMethodInfo m)
        {
            string nativeReturn = m.ReturnType == "void" ? "void" : MapNativeType(m.ReturnType);
            string fieldName = "_method_" + m.CsName;
            string delegateParamsFull = "IntPtr handle";
            foreach (var p in m.Parameters)
            {
                delegateParamsFull += ", " + MapNativeType(p.CsType) + " " + p.Name;
            }

            sb.AppendLine("        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]");
            sb.AppendLine("        private delegate " + nativeReturn + " Method" + m.CsName + "Delegate(" + delegateParamsFull + ");");
            sb.AppendLine("        private static Method" + m.CsName + "Delegate " + fieldName + ";");
            sb.AppendLine();
            sb.AppendLine("        private static " + nativeReturn + " NativeMethod" + m.CsName + "(" + delegateParamsFull + ")");
            sb.AppendLine("        {");
            sb.AppendLine("            var obj = ObjectHandle.Get<" + info.ClassName + ">(handle);");
            if (m.ReturnType == "void")
            {
                sb.AppendLine("            if (obj == null) return;");
            }
            else
            {
                sb.AppendLine("            if (obj == null) return default;");
            }

            string callArgs = BuildCallArgs(m.Parameters);
            if (m.ReturnType == "void")
            {
                sb.AppendLine("            obj." + m.CsName + "(" + callArgs + ");");
            }
            else if (m.ReturnType == "bool")
            {
                sb.AppendLine("            return obj." + m.CsName + "(" + callArgs + ") ? 1 : 0;");
            }
            else if (m.ReturnType == "string")
            {
                sb.AppendLine("            return Marshal.StringToHGlobalAnsi(obj." + m.CsName + "(" + callArgs + "));");
            }
            else
            {
                sb.AppendLine("            return obj." + m.CsName + "(" + callArgs + ");");
            }
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void EmitRegister(StringBuilder sb, BindClassInfo info)
        {
            sb.AppendLine("        public static void Register()");
            sb.AppendLine("        {");

            // Release function
            sb.AppendLine("            _releaseDelegate = new ReleaseDelegate(NativeRelease);");
            sb.AppendLine("            LuaNative.breadlua_set_release_fn(Marshal.GetFunctionPointerForDelegate(_releaseDelegate));");

            // Constructor
            if (info.Constructor != null)
            {
                sb.AppendLine("            _ctorDelegate = new ConstructorDelegate(NativeConstructor);");
                sb.AppendLine("            LuaNative.breadlua_register_fn(\"" + info.ClassName + ".new\", Marshal.GetFunctionPointerForDelegate(_ctorDelegate));");
            }

            // Property getters
            foreach (var prop in info.Properties)
            {
                if (prop.HasGetter)
                {
                    sb.AppendLine("            _get_" + prop.CsName + " = new Get" + prop.CsName + "Delegate(NativeGet" + prop.CsName + ");");
                    sb.AppendLine("            LuaNative.breadlua_register_fn(\"" + info.ClassName + ".get_" + prop.LuaName + "\", Marshal.GetFunctionPointerForDelegate(_get_" + prop.CsName + "));");
                }
            }

            // Property setters
            foreach (var prop in info.Properties)
            {
                if (prop.HasSetter)
                {
                    sb.AppendLine("            _set_" + prop.CsName + " = new Set" + prop.CsName + "Delegate(NativeSet" + prop.CsName + ");");
                    sb.AppendLine("            LuaNative.breadlua_register_fn(\"" + info.ClassName + ".set_" + prop.LuaName + "\", Marshal.GetFunctionPointerForDelegate(_set_" + prop.CsName + "));");
                }
            }

            // Methods
            foreach (var m in info.Methods)
            {
                sb.AppendLine("            _method_" + m.CsName + " = new Method" + m.CsName + "Delegate(NativeMethod" + m.CsName + ");");
                sb.AppendLine("            LuaNative.breadlua_register_fn(\"" + info.ClassName + "." + m.LuaName + "\", Marshal.GetFunctionPointerForDelegate(_method_" + m.CsName + "));");
            }

            sb.AppendLine("        }");
        }

        private static string BuildNativeParams(List<BindParamInfo> parameters)
        {
            if (parameters.Count == 0) return "";
            var parts = new List<string>();
            foreach (var p in parameters)
            {
                parts.Add(MapNativeType(p.CsType) + " " + p.Name);
            }
            return string.Join(", ", parts);
        }

        private static string BuildCallArgs(List<BindParamInfo> parameters)
        {
            var parts = new List<string>();
            foreach (var p in parameters)
            {
                if (p.CsType == "string")
                {
                    parts.Add("Marshal.PtrToStringAnsi(" + p.Name + ")");
                }
                else if (p.CsType == "bool")
                {
                    parts.Add(p.Name + " != 0");
                }
                else
                {
                    parts.Add(p.Name);
                }
            }
            return string.Join(", ", parts);
        }

        private static string MapNativeType(string csType)
        {
            switch (csType)
            {
                case "string": return "IntPtr";
                case "bool": return "int";
                case "int": return "int";
                case "long": return "long";
                case "float": return "float";
                case "double": return "double";
                default: return "IntPtr";
            }
        }
    }
}
