using System.Collections.Generic;
using System.Text;

namespace BreadPack.NativeLua.Generator.Bind
{
    internal static class BindCEmitter
    {
        public static string Emit(BindClassInfo info)
        {
            var sb = new StringBuilder();
            sb.AppendLine("/* <auto-generated/> */");
            sb.AppendLine("#include \"lua.h\"");
            sb.AppendLine("#include \"lauxlib.h\"");
            sb.AppendLine("#include <string.h>");
            sb.AppendLine();
            sb.AppendLine("extern void* breadlua_get_fn(const char* name);");
            sb.AppendLine("extern void* breadlua_get_object(lua_State* L, int index);");
            sb.AppendLine("extern void breadlua_push_object(lua_State* L, void* gc_handle, const char* mt_name);");
            sb.AppendLine();

            string mtName = "bread_" + info.ClassName;

            // Forward-declare bind, bound __index/__newindex, per-field closures, and method wrappers
            sb.AppendLine("static int l_" + info.ClassName + "_bind(lua_State* L);");
            sb.AppendLine("static int l_" + info.ClassName + "_bound_index(lua_State* L);");
            sb.AppendLine("static int l_" + info.ClassName + "_bound_newindex(lua_State* L);");
            foreach (var prop in info.Properties)
            {
                if (prop.HasGetter)
                    sb.AppendLine("static int l_" + info.ClassName + "_bind_get_" + prop.LuaName + "(lua_State* L);");
                if (prop.HasSetter)
                    sb.AppendLine("static int l_" + info.ClassName + "_bind_set_" + prop.LuaName + "(lua_State* L);");
            }
            foreach (var m in info.Methods)
            {
                sb.AppendLine("static int l_" + info.ClassName + "_" + m.LuaName + "(lua_State* L);");
                sb.AppendLine("static int l_" + info.ClassName + "_bound_" + m.LuaName + "(lua_State* L);");
            }
            sb.AppendLine();

            // Constructor
            if (info.Constructor != null)
            {
                EmitConstructor(sb, info, mtName);
            }

            // __index metamethod (property getters + method lookup)
            EmitIndex(sb, info);

            // __newindex metamethod (property setters)
            EmitNewIndex(sb, info);

            // Per-property getter/setter closures (handle as upvalue)
            EmitBindPropertyClosures(sb, info);

            // Per-method closures for bound tables (handle as upvalue)
            EmitBoundMethodClosures(sb, info);

            // Bound __index/__newindex (getters/setters table as upvalue, O(1) hash lookup)
            EmitBoundIndex(sb, info);
            EmitBoundNewIndex(sb, info);

            // bind() — builds getters/setters tables, creates metatable, returns bound table
            EmitBind(sb, info);

            // Method wrappers
            foreach (var m in info.Methods)
            {
                EmitMethodWrapper(sb, info, m);
            }

            // luaopen function
            EmitLuaOpen(sb, info, mtName);

            return sb.ToString();
        }

        private static void EmitConstructor(StringBuilder sb, BindClassInfo info, string mtName)
        {
            sb.AppendLine("typedef void* (*" + info.ClassName + "_ctor_fn)(" + BuildCtorCParams(info.Constructor.Parameters) + ");");
            sb.AppendLine();
            sb.AppendLine("static int l_" + info.ClassName + "_new(lua_State* L) {");
            sb.AppendLine("    " + info.ClassName + "_ctor_fn fn = (" + info.ClassName + "_ctor_fn)breadlua_get_fn(\"" + info.ClassName + ".new\");");
            sb.AppendLine("    if (!fn) return luaL_error(L, \"constructor not registered\");");

            int paramIdx = 1;
            foreach (var p in info.Constructor.Parameters)
            {
                sb.AppendLine("    " + MapCType(p.CsType) + " p" + paramIdx + " = " + GetLuaArg(p.CsType, paramIdx) + ";");
                paramIdx++;
            }

            string args = BuildCtorCallArgs(info.Constructor.Parameters);
            sb.AppendLine("    void* handle = fn(" + args + ");");
            sb.AppendLine("    breadlua_push_object(L, handle, \"" + mtName + "\");");
            sb.AppendLine("    return 1;");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        private static void EmitIndex(StringBuilder sb, BindClassInfo info)
        {
            sb.AppendLine("static int l_" + info.ClassName + "_index(lua_State* L) {");
            sb.AppendLine("    void* handle = breadlua_get_object(L, 1);");
            sb.AppendLine("    const char* key = luaL_checkstring(L, 2);");

            // bind() — returns closure table for real-time access
            sb.AppendLine("    if (strcmp(key, \"bind\") == 0) {");
            sb.AppendLine("        lua_pushcfunction(L, l_" + info.ClassName + "_bind);");
            sb.AppendLine("        return 1;");
            sb.AppendLine("    }");

            // Check methods first
            foreach (var m in info.Methods)
            {
                sb.AppendLine("    if (strcmp(key, \"" + m.LuaName + "\") == 0) {");
                sb.AppendLine("        lua_pushcfunction(L, l_" + info.ClassName + "_" + m.LuaName + ");");
                sb.AppendLine("        return 1;");
                sb.AppendLine("    }");
            }

            // Then property getters
            foreach (var prop in info.Properties)
            {
                if (!prop.HasGetter) continue;
                string getterFnType = MapCReturn(prop.CsType) + " (*)(void*)";
                sb.AppendLine("    if (strcmp(key, \"" + prop.LuaName + "\") == 0) {");
                sb.AppendLine("        " + getterFnType + " getter = (" + getterFnType + ")breadlua_get_fn(\"" + info.ClassName + ".get_" + prop.LuaName + "\");");
                sb.AppendLine("        if (getter) {");
                sb.AppendLine("            " + PushGetterResult(prop) + ";");
                sb.AppendLine("            return 1;");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
            }

            sb.AppendLine("    return 0;");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        private static void EmitNewIndex(StringBuilder sb, BindClassInfo info)
        {
            sb.AppendLine("static int l_" + info.ClassName + "_newindex(lua_State* L) {");
            sb.AppendLine("    void* handle = breadlua_get_object(L, 1);");
            sb.AppendLine("    const char* key = luaL_checkstring(L, 2);");

            foreach (var prop in info.Properties)
            {
                if (!prop.HasSetter) continue;
                string setterFnType = "void (*)(void*, " + MapCType(prop.CsType) + ")";
                sb.AppendLine("    if (strcmp(key, \"" + prop.LuaName + "\") == 0) {");
                sb.AppendLine("        " + setterFnType + " setter = (" + setterFnType + ")breadlua_get_fn(\"" + info.ClassName + ".set_" + prop.LuaName + "\");");
                sb.AppendLine("        if (setter) setter(handle, " + GetLuaArg(prop.CsType, 3) + ");");
                sb.AppendLine("        return 0;");
                sb.AppendLine("    }");
            }

            sb.AppendLine("    return luaL_error(L, \"unknown property: %s\", key);");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        private static void EmitMethodWrapper(StringBuilder sb, BindClassInfo info, BindMethodInfo m)
        {
            string fnPtrType = info.ClassName + "_" + m.CsName + "_fn";
            sb.AppendLine("typedef " + MapCReturn(m.ReturnType) + " (*" + fnPtrType + ")(void*" + BuildMethodCParamTypes(m.Parameters) + ");");
            sb.AppendLine();
            sb.AppendLine("static int l_" + info.ClassName + "_" + m.LuaName + "(lua_State* L) {");
            sb.AppendLine("    void* handle = breadlua_get_object(L, 1);");
            sb.AppendLine("    " + fnPtrType + " fn = (" + fnPtrType + ")breadlua_get_fn(\"" + info.ClassName + "." + m.LuaName + "\");");
            sb.AppendLine("    if (!fn) return luaL_error(L, \"method not registered: " + m.LuaName + "\");");

            int paramIdx = 2;
            foreach (var p in m.Parameters)
            {
                sb.AppendLine("    " + MapCType(p.CsType) + " p" + paramIdx + " = " + GetLuaArg(p.CsType, paramIdx) + ";");
                paramIdx++;
            }

            string callArgs = "handle";
            paramIdx = 2;
            foreach (var p in m.Parameters)
            {
                callArgs += ", p" + paramIdx;
                paramIdx++;
            }

            if (m.ReturnType == "void")
            {
                sb.AppendLine("    fn(" + callArgs + ");");
                sb.AppendLine("    return 0;");
            }
            else
            {
                sb.AppendLine("    " + MapCReturn(m.ReturnType) + " result = fn(" + callArgs + ");");
                sb.AppendLine("    " + PushCResult(m.ReturnType) + ";");
                sb.AppendLine("    return 1;");
            }
            sb.AppendLine("}");
            sb.AppendLine();
        }

        private static void EmitLuaOpen(StringBuilder sb, BindClassInfo info, string mtName)
        {
            sb.AppendLine("int luaopen_" + info.ClassName + "(lua_State* L) {");
            sb.AppendLine("    luaL_newmetatable(L, \"" + mtName + "\");");
            sb.AppendLine("    lua_pushcfunction(L, l_" + info.ClassName + "_index);");
            sb.AppendLine("    lua_setfield(L, -2, \"__index\");");
            sb.AppendLine("    lua_pushcfunction(L, l_" + info.ClassName + "_newindex);");
            sb.AppendLine("    lua_setfield(L, -2, \"__newindex\");");
            sb.AppendLine("    lua_pop(L, 1);");

            if (info.Constructor != null)
            {
                sb.AppendLine("    lua_pushcfunction(L, l_" + info.ClassName + "_new);");
                sb.AppendLine("    lua_setglobal(L, \"" + info.ClassName + "\");");
            }

            sb.AppendLine("    return 0;");
            sb.AppendLine("}");
        }

        private static void EmitBindPropertyClosures(StringBuilder sb, BindClassInfo info)
        {
            // Per-property getter closures: handle is upvalue index 1, called with 0 args, returns 1 value
            foreach (var prop in info.Properties)
            {
                if (prop.HasGetter)
                {
                    string getterFnType = MapCReturn(prop.CsType) + " (*)(void*)";
                    sb.AppendLine("static int l_" + info.ClassName + "_bind_get_" + prop.LuaName + "(lua_State* L) {");
                    sb.AppendLine("    void* handle = lua_touserdata(L, lua_upvalueindex(1));");
                    sb.AppendLine("    " + getterFnType + " getter = (" + getterFnType + ")breadlua_get_fn(\"" + info.ClassName + ".get_" + prop.LuaName + "\");");
                    sb.AppendLine("    " + PushValue(prop.CsType, "getter(handle)") + ";");
                    sb.AppendLine("    return 1;");
                    sb.AppendLine("}");
                    sb.AppendLine();
                }

                if (prop.HasSetter)
                {
                    string setterFnType = "void (*)(void*, " + MapCType(prop.CsType) + ")";
                    sb.AppendLine("static int l_" + info.ClassName + "_bind_set_" + prop.LuaName + "(lua_State* L) {");
                    sb.AppendLine("    void* handle = lua_touserdata(L, lua_upvalueindex(1));");
                    sb.AppendLine("    " + setterFnType + " setter = (" + setterFnType + ")breadlua_get_fn(\"" + info.ClassName + ".set_" + prop.LuaName + "\");");
                    sb.AppendLine("    setter(handle, " + GetLuaArg(prop.CsType, 1) + ");");
                    sb.AppendLine("    return 0;");
                    sb.AppendLine("}");
                    sb.AppendLine();
                }
            }
        }

        private static void EmitBoundMethodClosures(StringBuilder sb, BindClassInfo info)
        {
            // Per-method closures for bound tables: handle from upvalue, : syntax means self is arg 1
            foreach (var m in info.Methods)
            {
                string fnPtrType = info.ClassName + "_" + m.CsName + "_bound_fn";
                sb.AppendLine("typedef " + MapCReturn(m.ReturnType) + " (*" + fnPtrType + ")(void*" + BuildMethodCParamTypes(m.Parameters) + ");");
                sb.AppendLine();
                sb.AppendLine("static int l_" + info.ClassName + "_bound_" + m.LuaName + "(lua_State* L) {");
                sb.AppendLine("    void* handle = lua_touserdata(L, lua_upvalueindex(1));");
                sb.AppendLine("    " + fnPtrType + " fn = (" + fnPtrType + ")breadlua_get_fn(\"" + info.ClassName + "." + m.LuaName + "\");");
                sb.AppendLine("    if (!fn) return luaL_error(L, \"method not registered: " + m.LuaName + "\");");

                // : syntax passes self as arg 1, real params start at 2
                int paramIdx = 2;
                foreach (var p in m.Parameters)
                {
                    sb.AppendLine("    " + MapCType(p.CsType) + " p" + paramIdx + " = " + GetLuaArg(p.CsType, paramIdx) + ";");
                    paramIdx++;
                }

                string callArgs = "handle";
                paramIdx = 2;
                foreach (var p in m.Parameters)
                {
                    callArgs += ", p" + paramIdx;
                    paramIdx++;
                }

                if (m.ReturnType == "void")
                {
                    sb.AppendLine("    fn(" + callArgs + ");");
                    sb.AppendLine("    return 0;");
                }
                else
                {
                    sb.AppendLine("    " + MapCReturn(m.ReturnType) + " result = fn(" + callArgs + ");");
                    sb.AppendLine("    " + PushCResult(m.ReturnType) + ";");
                    sb.AppendLine("    return 1;");
                }
                sb.AppendLine("}");
                sb.AppendLine();
            }
        }

        private static void EmitBoundIndex(StringBuilder sb, BindClassInfo info)
        {
            // __index with getters table as upvalue: rawget O(1) hash lookup instead of strcmp O(N)
            sb.AppendLine("static int l_" + info.ClassName + "_bound_index(lua_State* L) {");
            sb.AppendLine("    lua_pushvalue(L, 2);");
            sb.AppendLine("    lua_rawget(L, lua_upvalueindex(1));");
            sb.AppendLine("    if (lua_isfunction(L, -1)) {");
            sb.AppendLine("        lua_call(L, 0, 1);");
            sb.AppendLine("        return 1;");
            sb.AppendLine("    }");
            sb.AppendLine("    return 0;");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        private static void EmitBoundNewIndex(StringBuilder sb, BindClassInfo info)
        {
            // __newindex with setters table as upvalue: rawget O(1) hash lookup
            sb.AppendLine("static int l_" + info.ClassName + "_bound_newindex(lua_State* L) {");
            sb.AppendLine("    lua_pushvalue(L, 2);");
            sb.AppendLine("    lua_rawget(L, lua_upvalueindex(1));");
            sb.AppendLine("    if (lua_isfunction(L, -1)) {");
            sb.AppendLine("        lua_pushvalue(L, 3);");
            sb.AppendLine("        lua_call(L, 1, 0);");
            sb.AppendLine("        return 0;");
            sb.AppendLine("    }");
            sb.AppendLine("    return 0;");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        private static void EmitBind(StringBuilder sb, BindClassInfo info)
        {
            // Count entries for getters table (properties + methods) and setters table
            int getterCount = 0;
            int setterCount = 0;
            foreach (var prop in info.Properties)
            {
                if (prop.HasGetter) getterCount++;
                if (prop.HasSetter) setterCount++;
            }
            getterCount += info.Methods.Count;

            sb.AppendLine("static int l_" + info.ClassName + "_bind(lua_State* L) {");
            sb.AppendLine("    void* handle = breadlua_get_object(L, 1);");
            sb.AppendLine("    if (!handle) return luaL_error(L, \"null object\");");
            sb.AppendLine();

            // Build getters table: { fieldName -> getter_closure(handle_upvalue), methodName -> method_closure(handle_upvalue) }
            sb.AppendLine("    lua_createtable(L, 0, " + getterCount + ");");
            foreach (var prop in info.Properties)
            {
                if (!prop.HasGetter) continue;
                sb.AppendLine("    lua_pushlightuserdata(L, handle);");
                sb.AppendLine("    lua_pushcclosure(L, l_" + info.ClassName + "_bind_get_" + prop.LuaName + ", 1);");
                sb.AppendLine("    lua_setfield(L, -2, \"" + prop.LuaName + "\");");
            }
            foreach (var m in info.Methods)
            {
                sb.AppendLine("    lua_pushlightuserdata(L, handle);");
                sb.AppendLine("    lua_pushcclosure(L, l_" + info.ClassName + "_bound_" + m.LuaName + ", 1);");
                sb.AppendLine("    lua_setfield(L, -2, \"" + m.LuaName + "\");");
            }
            sb.AppendLine("    int getters_idx = lua_gettop(L);");
            sb.AppendLine();

            // Build setters table: { fieldName -> setter_closure(handle_upvalue) }
            sb.AppendLine("    lua_createtable(L, 0, " + setterCount + ");");
            foreach (var prop in info.Properties)
            {
                if (!prop.HasSetter) continue;
                sb.AppendLine("    lua_pushlightuserdata(L, handle);");
                sb.AppendLine("    lua_pushcclosure(L, l_" + info.ClassName + "_bind_set_" + prop.LuaName + ", 1);");
                sb.AppendLine("    lua_setfield(L, -2, \"" + prop.LuaName + "\");");
            }
            sb.AppendLine("    int setters_idx = lua_gettop(L);");
            sb.AppendLine();

            // Create result table (empty)
            sb.AppendLine("    lua_createtable(L, 0, 0);");
            sb.AppendLine();

            // Create metatable with __index (getters upvalue) and __newindex (setters upvalue)
            sb.AppendLine("    lua_createtable(L, 0, 2);");
            sb.AppendLine();
            sb.AppendLine("    lua_pushvalue(L, getters_idx);");
            sb.AppendLine("    lua_pushcclosure(L, l_" + info.ClassName + "_bound_index, 1);");
            sb.AppendLine("    lua_setfield(L, -2, \"__index\");");
            sb.AppendLine();
            sb.AppendLine("    lua_pushvalue(L, setters_idx);");
            sb.AppendLine("    lua_pushcclosure(L, l_" + info.ClassName + "_bound_newindex, 1);");
            sb.AppendLine("    lua_setfield(L, -2, \"__newindex\");");
            sb.AppendLine();

            // Set metatable on result table
            sb.AppendLine("    lua_setmetatable(L, -2);");
            sb.AppendLine();

            // Remove getters/setters tables from stack (result table is on top)
            sb.AppendLine("    lua_remove(L, getters_idx);");
            sb.AppendLine("    lua_remove(L, setters_idx < getters_idx ? setters_idx : setters_idx - 1);");
            sb.AppendLine();
            sb.AppendLine("    return 1;");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        private static string PushValue(string csType, string expr)
        {
            switch (csType)
            {
                case "int": return "lua_pushinteger(L, " + expr + ")";
                case "long": return "lua_pushinteger(L, " + expr + ")";
                case "float": return "lua_pushnumber(L, " + expr + ")";
                case "double": return "lua_pushnumber(L, " + expr + ")";
                case "bool": return "lua_pushboolean(L, " + expr + ")";
                case "string": return "lua_pushstring(L, (const char*)" + expr + ")";
                default: return "lua_pushnil(L)";
            }
        }

private static string MapCType(string csType)
        {
            switch (csType)
            {
                case "int": return "int";
                case "long": return "long long";
                case "float": return "float";
                case "double": return "double";
                case "bool": return "int";
                case "string": return "const char*";
                default: return "void*";
            }
        }

        private static string MapCReturn(string csType)
        {
            switch (csType)
            {
                case "void": return "void";
                case "int": return "int";
                case "long": return "long long";
                case "float": return "float";
                case "double": return "double";
                case "bool": return "int";
                case "string": return "const char*";
                default: return "void*";
            }
        }

        private static string GetLuaArg(string csType, int idx)
        {
            switch (csType)
            {
                case "int": return "(int)luaL_checkinteger(L, " + idx + ")";
                case "long": return "(long long)luaL_checkinteger(L, " + idx + ")";
                case "float": return "(float)luaL_checknumber(L, " + idx + ")";
                case "double": return "luaL_checknumber(L, " + idx + ")";
                case "bool": return "lua_toboolean(L, " + idx + ")";
                case "string": return "luaL_checkstring(L, " + idx + ")";
                default: return "lua_touserdata(L, " + idx + ")";
            }
        }

        private static string PushGetterResult(BindPropertyInfo prop)
        {
            string call = "getter(handle)";
            switch (prop.CsType)
            {
                case "int": return "lua_pushinteger(L, " + call + ")";
                case "long": return "lua_pushinteger(L, " + call + ")";
                case "float": return "lua_pushnumber(L, " + call + ")";
                case "double": return "lua_pushnumber(L, " + call + ")";
                case "bool": return "lua_pushboolean(L, " + call + ")";
                case "string": return "lua_pushstring(L, (const char*)" + call + ")";
                default: return "lua_pushnil(L)";
            }
        }

        private static string PushCResult(string csType)
        {
            switch (csType)
            {
                case "int": return "lua_pushinteger(L, result)";
                case "long": return "lua_pushinteger(L, result)";
                case "float": return "lua_pushnumber(L, result)";
                case "double": return "lua_pushnumber(L, result)";
                case "bool": return "lua_pushboolean(L, result)";
                case "string": return "lua_pushstring(L, result)";
                default: return "lua_pushnil(L)";
            }
        }

        private static string BuildMethodCParamTypes(List<BindParamInfo> parameters)
        {
            var sb = new StringBuilder();
            foreach (var p in parameters)
            {
                sb.Append(", " + MapCType(p.CsType));
            }
            return sb.ToString();
        }

        private static string BuildCtorCParams(List<BindParamInfo> parameters)
        {
            if (parameters.Count == 0) return "void";
            var parts = new List<string>();
            foreach (var p in parameters)
            {
                parts.Add(MapCType(p.CsType) + " " + p.Name);
            }
            return string.Join(", ", parts);
        }

        private static string BuildCtorCallArgs(List<BindParamInfo> parameters)
        {
            var parts = new List<string>();
            int idx = 1;
            foreach (var p in parameters)
            {
                parts.Add("p" + idx);
                idx++;
            }
            return string.Join(", ", parts);
        }
    }
}
