using System.Text;

namespace BreadPack.NativeLua.Generator.Bind
{
    internal static class BindLuaEmitter
    {
        public static string Emit(BindClassInfo info)
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- <auto-generated/>");
            sb.AppendLine("-- " + info.ClassName + " Lua wrapper");
            sb.AppendLine("-- Object creation: local obj = " + info.ClassName + "(args...)");
            sb.AppendLine("-- Property access: obj.PropName");
            sb.AppendLine("-- Method call: obj:MethodName(args...)");
            return sb.ToString();
        }
    }
}
