using System.Text;
using BreadPack.NativeLua.Generator.Util;

namespace BreadPack.NativeLua.Generator.Bridge
{
    internal static class BridgeCEmitter
    {
        public static string Emit(BridgeStructInfo info)
        {
            var sb = new StringBuilder();
            sb.AppendLine("/* <auto-generated/> */");
            sb.AppendLine("#include \"lua.h\"");
            sb.AppendLine("#include \"lauxlib.h\"");
            sb.AppendLine();

            sb.AppendLine("typedef struct {");
            foreach (var f in info.Fields)
            {
                sb.AppendLine("    " + TypeMapper.ToCType(f.CsType) + " " + f.CsName + ";");
            }
            sb.AppendLine("} bread_" + info.LuaName + "_t;");
            sb.AppendLine();

            sb.AppendLine("static bread_" + info.LuaName + "_t* g_" + info.LuaName + "_data = NULL;");
            sb.AppendLine("static int g_" + info.LuaName + "_count = 0;");
            sb.AppendLine();

            sb.AppendLine("static int l_" + info.LuaName + "_init(lua_State* L) {");
            sb.AppendLine("    g_" + info.LuaName + "_data = (bread_" + info.LuaName + "_t*)lua_touserdata(L, 1);");
            sb.AppendLine("    g_" + info.LuaName + "_count = (int)luaL_checkinteger(L, 2);");
            sb.AppendLine("    return 0;");
            sb.AppendLine("}");
            sb.AppendLine();

            foreach (var f in info.Fields)
            {
                sb.AppendLine("static int l_" + info.LuaName + "_get_" + f.LuaName + "(lua_State* L) {");
                sb.AppendLine("    int idx = (int)luaL_checkinteger(L, 1);");
                sb.AppendLine("    luaL_argcheck(L, idx >= 0 && idx < g_" + info.LuaName + "_count, 1, \"index out of range\");");
                sb.AppendLine("    " + TypeMapper.ToLuaPush(f.CsType) + "(L, g_" + info.LuaName + "_data[idx]." + f.CsName + ");");
                sb.AppendLine("    return 1;");
                sb.AppendLine("}");
                sb.AppendLine();

                if (!f.IsReadOnly)
                {
                    sb.AppendLine("static int l_" + info.LuaName + "_set_" + f.LuaName + "(lua_State* L) {");
                    sb.AppendLine("    int idx = (int)luaL_checkinteger(L, 1);");
                    sb.AppendLine("    luaL_argcheck(L, idx >= 0 && idx < g_" + info.LuaName + "_count, 1, \"index out of range\");");
                    sb.AppendLine("    g_" + info.LuaName + "_data[idx]." + f.CsName + " = " + TypeMapper.ToCCast(f.CsType) + TypeMapper.ToLuaCheck(f.CsType) + "(L, 2);");
                    sb.AppendLine("    return 0;");
                    sb.AppendLine("}");
                    sb.AppendLine();
                }
            }

            sb.AppendLine("static const luaL_Reg " + info.LuaName + "_lib[] = {");
            sb.AppendLine("    {\"init\", l_" + info.LuaName + "_init},");
            foreach (var f in info.Fields)
            {
                sb.AppendLine("    {\"get_" + f.LuaName + "\", l_" + info.LuaName + "_get_" + f.LuaName + "},");
                if (!f.IsReadOnly)
                    sb.AppendLine("    {\"set_" + f.LuaName + "\", l_" + info.LuaName + "_set_" + f.LuaName + "},");
            }
            sb.AppendLine("    {NULL, NULL}");
            sb.AppendLine("};");
            sb.AppendLine();

            sb.AppendLine("int luaopen_" + info.LuaName + "(lua_State* L) {");
            sb.AppendLine("    luaL_newlib(L, " + info.LuaName + "_lib);");
            sb.AppendLine("    return 1;");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}
