using System.Text;

namespace BreadPack.NativeLua.Generator.Bridge
{
    internal static class BridgeLuaEmitter
    {
        public static string Emit(BridgeStructInfo info)
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- <auto-generated/>");
            sb.AppendLine("local raw = require(\"" + info.LuaName + "\")");
            sb.AppendLine();
            sb.AppendLine("local " + info.TypeName + " = {}");
            sb.AppendLine(info.TypeName + ".__index = " + info.TypeName);
            sb.AppendLine();

            sb.AppendLine("function " + info.TypeName + ".get(idx)");
            sb.AppendLine("    return setmetatable({ _idx = idx }, " + info.TypeName + ")");
            sb.AppendLine("end");
            sb.AppendLine();

            foreach (var f in info.Fields)
            {
                sb.AppendLine("function " + info.TypeName + ":" + f.LuaName + "()");
                sb.AppendLine("    return raw.get_" + f.LuaName + "(self._idx)");
                sb.AppendLine("end");
                sb.AppendLine();

                if (!f.IsReadOnly)
                {
                    sb.AppendLine("function " + info.TypeName + ":set_" + f.LuaName + "(v)");
                    sb.AppendLine("    raw.set_" + f.LuaName + "(self._idx, v)");
                    sb.AppendLine("end");
                    sb.AppendLine();
                }
            }

            sb.AppendLine("function " + info.TypeName + ".count()");
            sb.AppendLine("    return g_" + info.LuaName + "_count");
            sb.AppendLine("end");
            sb.AppendLine();
            sb.AppendLine("return " + info.TypeName);
            return sb.ToString();
        }
    }
}
