using System.Text;

namespace BreadPack.NativeLua.Generator.Bridge
{
    internal static class BridgeCSharpEmitter
    {
        public static string Emit(BridgeStructInfo info)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Runtime.InteropServices;");
            sb.AppendLine("using BreadPack.NativeLua;");
            sb.AppendLine();
            sb.AppendLine("namespace " + info.Namespace);
            sb.AppendLine("{");
            sb.AppendLine("    public static unsafe class " + info.TypeName + "Bridge");
            sb.AppendLine("    {");
            sb.AppendLine("        private static " + info.TypeName + "* _buffer;");
            sb.AppendLine("        private static int _capacity;");
            sb.AppendLine("        private static int _count;");
            sb.AppendLine("        private static IntPtr _handle;");
            sb.AppendLine();
            sb.AppendLine("        public static int Count { get { return _count; } set { _count = Math.Clamp(value, 0, _capacity); } }");
            sb.AppendLine();
            sb.AppendLine("        public static void Initialize(int capacity)");
            sb.AppendLine("        {");
            sb.AppendLine("            _capacity = capacity;");
            sb.AppendLine("            _handle = Marshal.AllocHGlobal(sizeof(" + info.TypeName + ") * capacity);");
            sb.AppendLine("            _buffer = (" + info.TypeName + "*)_handle;");
            sb.AppendLine("            new Span<byte>((void*)_handle, sizeof(" + info.TypeName + ") * capacity).Clear();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static ref " + info.TypeName + " Get(int index)");
            sb.AppendLine("        {");
            sb.AppendLine("            if ((uint)index >= (uint)_count) throw new IndexOutOfRangeException();");
            sb.AppendLine("            return ref _buffer[index];");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static void BindToLua(LuaState state)");
            sb.AppendLine("        {");
            sb.AppendLine("            state.SetGlobal(\"g_" + info.LuaName + "\", (IntPtr)_buffer);");
            sb.AppendLine("            state.SetGlobal(\"g_" + info.LuaName + "_count\", _count);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static void Dispose()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (_handle != IntPtr.Zero)");
            sb.AppendLine("            {");
            sb.AppendLine("                Marshal.FreeHGlobal(_handle);");
            sb.AppendLine("                _handle = IntPtr.Zero;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
